### ISSUE TITLE
/bin/sh: /BingRewards/notify/onComplete.sh: No such file or directory

### ISSUE THREAD

**Issue by ds1239** [sealemar/BingRewards#154]
Hello. I keep getting the following error: "/bin/sh: /BingRewards/notify/onComplete.sh: No such file or directory" after each account, yet I see that the file is there. Please help

**Comment by PlasmaPower** [comment]
Are you sure that the file exists in the root directory? You might have to make it relative to your home folder or something.

**Comment by ds1239** [comment]
The BingBot folder is located at Users/User/BingBot, but I changed the paths in the config file.

**Comment by jamesalmeida** [comment]
I was having the same problem. Remove the starting `/` so it becomes a relative path rather than an absolute path. So then you only need to tell it where the `notify` folder is relative to the `main.py` file. My original config had the path `/home/BingRewards/bin/BingRewards/notify/onComplete_reached.sh`
and it didn't work. When I changed those paths to `notify/onComplete_reached.sh` it started to work.
