### ISSUE TITLE
Switch to Microsoft Rewards

### ISSUE THREAD

**Issue by duddles** [sealemar/BingRewards#201]
Just wondering if there will be an effort to make BingRewards compatible with the new Microsoft Rewards system starting today?

**Comment by jamesalmeida** [comment]
It will interesting to see if this will still work at all or completely break

**Comment by amayer5125** [comment]
It seems it doesnt work with Microsoft Rewards. One of my accounts got moved over and it doesnt work. If you have any time to put into pull requests I would be happy to look at them.

**Comment by baltimoron** [comment]
I'm only really seeing two issues:

-It doesn't count the number of searches needed. I'm thinking they just changed the wording and the fix might be as simple as changing the RE used in the flyout parser. For now, you can hardcode the number of searches and it will accrue points as expected.

-The authentication system needs to be changed to use https://account.microsoft.com/rewards/. Currently, the script can still log into bing and collect points for searches but can't access the microsoft rewards homepage in order to get your point totals. There are also a couple of html tags that need to be changed but that should be trivial.

I'm working on both of these but I think the authentication stuff is a little bit over my head, will update if I make any progress.

**Comment by amayer5125** [comment]
@baltimoron awesome job! Every little bit helps. If you post any pull requests Ill test them out on my account.

**Comment by baltimoron** [comment]
Actually it looks like I spoke too soon on the search issue, they aren't getting any points. Still looking into it.

For the authentication issue, if you can live without it (for now) just comment out the call to the getLifetimeCredits method and it will exit successfully.

**Comment by amayer5125** [comment]
I think its time for an overhaul. All my accounts are Microsoft Rewards now.

**Comment by benparsell** [comment]
Agreed @amayer5125. Is it possible to use the existing foundation and just re-write the auth class for Microsoft?

**Comment by amayer5125** [comment]
This is fixed with #202

**Comment by amayer5125** [comment]
This is fixed with #202
