### ISSUE TITLE
Total Points Earned: 0 / No Results Page

### ISSUE THREAD

**Issue by FunkyEssence** [sealemar/BingRewards#214]
Hello,

I've had this issue since starting to use this script. I'm not sure if everyone has this issue, or if it is just me. 

Attached is the log for one of my config files. I have 5 separate config files that run with multiple accounts -- all of them repeat this sequence in the log file.

First, I receive an Error 302 right from the start. Every time. I'm not sure what is causing this, or how to debug it. Once retry number 2 starts, both PC & Mobile searches run. Immediately after that, I get another Error 302. Retry #3, is another error 302, etc. (I have set the # of retries to 5). Then it will skip to the next account. 

At the end of the script, it also shows "Total points earned: 0". I am also not getting a results output since after looking at the script, I believe it does not output the results page unless the points earned are greater than zero. 

As I said, this sequence of Error 302, PC/Mobile, Error 302 happens to every account in the same exact order. It still happens with or without using a proxy.

Does anyone have this issue? Has anyone encountered this and fixed it? I would really like the script to output the results and run without these errors as the errors cause the script to run longer than it should. 

[log.txt](https://github.com/sealemar/BingRewards/files/549214/log.txt)

**Comment by raulshum** [comment]
Did you ever get a update on this.. i'm having the same issue

**Comment by puternutt** [comment]
I've noticed this is a hit and miss, some days I have the results page up and I can see them and maybe one account has points added and the rest are blank, other days, 3 are done and the rest are not, then I rerun the script and the ones just completed are blanks (of course) and the ones that were missed are now showing finished. So I just run the script, then run it again almost back to back. Seems to get all of them. But the results page doesn't show every single time. So I have a request (suggestion) 

Could you (one of the developers) write a script that reads ONLY the results page so that we can just run it and it just goes out and grabs the account data and displays the points for that day?

**Comment by amayer5125** [comment]
This should be fixed in newest version.
