### ISSUE TITLE
No RegEx matches found for this search and earn

### ISSUE THREAD

**Issue by duddles** [sealemar/BingRewards#216]
Today the mobile searches ran but not the PC searches - maybe it is something to do with a 2X search offer for Saturday and Sunday in December?

Just wondering if anyone else had issues with this today or if there is something I could try, thanks

**Comment by Harrysachz** [comment]
Came here to see if I was the only one. The 2x weekend is a likely culprit.

**Comment by FunkyEssence** [comment]
I have several accounts that have double points every day in december. These accounts arent getting any pc searches completed

**Comment by carterschieffer** [comment]
It looks like this is happening because the "SEARCH_AND_EARN_DESCR_RE" RegEx isn't matching on these double days because the description is slightly different.

"Earn up to 300 points today, 10 points per search on PC."
VS
"Earn up to 200 points per day, 10 points per search on PC."

I believe I've got this fixed on my local copy, so I'll try to submit a pull request for this.

**Comment by specu** [comment]
Your fix worked for me. Hopefully you'll find a bit more time to put into this project! (handling quizzes, error handling, ms edge daily activity, security prompts).

**Comment by Vixine** [comment]
Your fix works for me too.
