### ISSUE TITLE
help, script not running just errors out

### ISSUE THREAD

**Issue by gamerinamask93** [sealemar/BingRewards#280]
hey guys, it seems like it is dead again or on myside it seems it is,
earlier today it was not loading two of the four accounts in the config.xml

it just runs like the following every time:
```
root@amlogic:~/BingRewards# python main.py
2017-10-04 16:29:24.0 - script started
--------------------------------------------------------------------------------

Live - (REDACTED)@gmail.com

For: Live - (REDACTED)@gmail.com

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail

```
if anyone can help me out here i would be very grateful, its hurting my brain lol.. i am kinda new to python i am pretty much open to most of the suggestions or even redownloading a different branch aslong as it works... i have no idea what is actually causing it

oh also for a bit more info i will run with -v

```
root@amlogic:~/BingRewards# python main.py -v
2017-10-04 16:36:12.3 - script started
--------------------------------------------------------------------------------

Reward 1/1:
-----------
name        :
description :

Live - (REDACTED)@gmail.com

For: Live - (REDACTED)@gmail.com

--------------------------------------------------------------------------------

Full log:
---------
Empty log
onScriptFailure: -mail
```

**Comment by gamerinamask93** [comment]
**UPDATE**
okay so i just spent 43 ish mins looking into it and it looks like a brand new deploy of the script and a manual rewrite of config.xml fixes the issue.. so somehow my config became corrupted.

i will just leave this here so anyone else getting this knows what to do

**Comment by specu** [comment]
I dont see anything here that would help others getting similar issues to get it to work. perhaps you want to adjust/append documentation and create a pull request for it?

**Comment by fraser1974** [comment]
I'm getting the same problem on only one of my accounts. Any other solutions? I tried redoing the config file.

**Comment by gamerinamask93** [comment]
if you are having issues still, please try https://github.com/baltimoron/BingRewards baltimorons branch, i have tested and it didnt have any issues

**Comment by fraser1974** [comment]
Hey, yeah, it works for the most part. I get one of these after every account: 
Result 1/15:
-----------
name        : Browse & earn
url         : https://www.bing.com/explore/rewards-browse-and-earn?FORM=ML13VT&CREA=ML13VT&wt.mc_id=ML13VT&rnoreward=1
progressCur : 0
progressMax : 150
progress %  : 0.00%
description : Earn up to 150 points per month, 5 points per hour, for actively browsing with Microsoft Edge. Counter updates daily.
   Error    :   true
   Message  : Didn't earn any points for click
   Action   : warn

But it hasn't effected the searches. The script for 6 accounts seems to be taking a long time though, longer than usual. Not sure if it's something you did or if it's because of that error. Doesn't make a difference to me. Thanks!

**Comment by amayer5125** [comment]
I am reviewing #284 which should fix this issue.
