### ISSUE TITLE
AuthenticationError

### ISSUE THREAD

**Issue by enzo-code** [sealemar/BingRewards#285]
AuthenticationError:
Could not find variable 't' on Live login page

**Comment by amayer5125** [comment]
What version of BingRewards are you using?

**Comment by enzo-code** [comment]
An old one, most likely. How do I get it so that it automatically updates with the same config?

**Comment by amayer5125** [comment]
You can not automatically update but if you download a new version and unzip it into the same folder it will not overwrite your config file. We do not distribute a file with the same name as the configuration file for that exact reason.

There are some other issues with the current version but we are trying to resolve them with open pull requests.

I am going to close this issue as I believe this issue was already resolved and is no longer an issue in the current version. If you have another issue with the current version please search the open issues and open a new one if needed.
