### ISSUE TITLE
error substring not found

### ISSUE THREAD

**Issue by specu** [sealemar/BingRewards#334]
I got 2 of those today and 1 yesterday. I'll try to build in stack trace reporting into onfailure and see if I can pinpoint it. The script runs fine on retry.

**Comment by baltimoron** [comment]
Line 185 in bingDashboardParser: s = page.index("t.innerHTML='")

Since it's related to html parsing and runs on retry I'm guessing it's another issue related to the page not fully loaded like the CRC check. If you add a catch for valueerror in the earnRewards method in main it will auto-retry (assuming your retry value is > 1)

**Comment by baltimoron** [comment]
I'll post the entire stack trace in a few hours when I get home.

**Comment by specu** [comment]
any chance you could commit the mobile search pull request? my accounts are set to git pull automatically so it would be nice to get that fixed that way :)

**Comment by baltimoron** [comment]
Done.

**Comment by baltimoron** [comment]
Ok turns out I don't have this stack trace in my history anymore so I can't post it. If I have some time tomorrow I'll disable the exception check and see if I can figure out what's going on here.

**Comment by specu** [comment]
I'm not able to reproduce that problem at the moment, so it's not a big deal yet.

**Comment by baltimoron** [comment]
Latest commit has a catch for this.
