### ISSUE TITLE
Non-US Accounts Don't Work?

### ISSUE THREAD

**Issue by godlessfather** [sealemar/BingRewards#344]
Can someone confirm the "US region only" @S3phi40T mentioned in #341? I've been trying to help a Canadian friend set this up and can't seem to make it work for him there, but can run the script successfully in here in the US. It logs in to his hotmail account but immediately moves on to

`Full log:`
`---------`
`Empty log`
`onScriptFailure: -mail`

**Comment by S3phi40T** [comment]
Believe me, I know what I'm talking about.
Script is set up for Level 2, US region only. Period.
Maybe @baltimoron  change that for new dashboard but I don't know.

I have tested rewards in all 6 regions - US, CA, UK, AU, GER, FR (now it's only 3 regions).
Other regions have different amount of points per searches. 150 + 100 + 20 US against 90  60 + 20.
With all regions combined (before they blocked it) I was able to gather 1K points per day from searches only + quizes, etc. 

Because of that, I have wrote simple autohotkey search script combined with Chrome extensions for user agent switch, so I was able to perform similar tasks by using Windows. It still helps me if this script fails.

Unfortunately first batch of my accounts was banned (rewards suspended) because all rewards services were activated with the same phone number (you can't have multiple accounts EULA violation). 

Then with second batch wasn't even suspended, but because of VPN jumping through regions they flagged my account with "suspicious behaviour detected" email and refused to redeem points (please contact support) - contact is email only and they reply with generic response that I'm not US citizen and I can piss off.

Anyways, now I use US region only, have all rewards accounts activated with different US phone number (during first redeem) and it's all fine so far.

...I only miss my almost 100K of lost points and 1K+ daily earns. 

Don't try switching regions with VPN (they blocked collecting points form other regions anyway so only clicks and quizes left)  because it's ban bomb with long fuse.

Regards

**Comment by godlessfather** [comment]
Here's the traceback if it helps:

```
Traceback (most recent call last):
  File "./main.py", line 281, in <module>
    __run(config)
  File "./main.py", line 206, in __run
    __processAccount(config, httpHeaders, agents, reportItem, account.password)
  File "./main.py", line 168, in __processAccount
    earnRewards(config, httpHeaders, userAgents, reportItem, accountPassword)
  File "./main.py", line 56, in earnRewards
    rewards = bdp.parseDashboardPage(bingRewards.getDashboardPage(), bingCommon.ACCOUNT_URL)
  File "./pkg/bingDashboardParser.py", line 168, in parseDashboardPage
    rewardProgressMax = int(rDscSplit[rDscSplit.index('points.')-1])
ValueError: 'points.' is not in list
```

**Comment by aliasfoxkde** [comment]
@S3phi40T not to argue with you but I redeem 5 accounts using one number. I know the EULA states "You may not maintain more than one Program account (“Account”). Each household is limited to five Accounts". But I've always taken that as being allowed to only have 1 account per person, but being allowed to have only one phone number per household. Like a land line service that many people may share. And while I've gotten dummy accounts banned for other reasons, I've never had my 5 primary accounts banned for redeeming using one phone. On the safe side, I do stagger redemption several days or weeks apart per account but I have redeemed multiple rewards at a time on that one account. I don't think I'm a special case, so I figure I'm doing something right. Thanks

**Comment by rustyshackleford2017** [comment]
@S3phi40T Thank you thank you thank you for this info. Was wondering about all sorts of stuff that you succinctly answered in that one golden post! @aliasfoxkde I hope your right about the phone number cause I am only using one...so far it works for me too.

**Comment by godlessfather** [comment]
Closing this thanks to @dreded (at least for Canadian accounts).
