### ISSUE TITLE
requests module is missing

### ISSUE THREAD

**Issue by gstreak** [sealemar/BingRewards#345]
Getting the below error after today's "git pull" from @baltimoron fork:

Traceback (most recent call last):
  File "./main.py", line 24, in <module>
    from bingRewards import BingRewards
  File "./pkg/bingRewards.py", line 22, in <module>
    import requests
ImportError: No module named requests

**Comment by baltimoron** [comment]
I thought the requests module was always included with python but apparently not. Do pip install requests.

**Comment by gstreak** [comment]
that was fast. Works like a charm now, thanks @baltimoron

**Comment by specu** [comment]
it would be great to integrate both requests and bs4 into code tree, if the license is compatible. I'm not good at those things.

**Comment by coollbv** [comment]
I already had pip installed but reinstalled it just in case. I still get this...

C:\Python27>python get-pip.py
Requirement already up-to-date: pip in c:\python27\lib\site-packages
Collecting wheel
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |################################| 51kB 241kB/s
Installing collected packages: wheel
Successfully installed wheel-0.30.0

C:\Python27>cd..

C:\>cd bing

C:\bing>main.py
Traceback (most recent call last):
  File "C:\bing\main.py", line 24, in <module>
    from bingRewards import BingRewards
  File "C:\bing\pkg\bingRewards.py", line 22, in <module>
    import requests
ImportError: No module named requests

**Comment by coollbv** [comment]
I just had to use :>easy_installs.exe requests on Windows

**Comment by specu** [comment]
@coollbv http://docs.python-requests.org/en/master/user/install/
"Once you have a copy of the source, you can embed it in your own Python package"
just like bs4 directory

**Comment by baltimoron** [comment]
I'll add it to requirements.txt (bs4 is already in there). Then you can just do "pip install -r requirements.txt" and it should take care of everything.

**Comment by specu** [comment]
@baltimoron I've submitted a patch that achieves the same thing without the need for requests module (since it's only 1 call and there's ton of problems stemming from it).
On top of that I think doing this the requests module way does not support the proxy setting.
If approved, I guess requirements would have to be reversed and the whole support for new dashboard justifies a version bump with date update.

**Comment by specu** [comment]
if you're going to put together a pull request out of that, you might want to get rid of profanities from comments to increase chances of the patch being accepted on first try....

**Comment by S3phi40T** [comment]
@specu, today morning I have tested @baltimoron latest commit (with requests) and it worked over VPN I use. ;)

**Comment by specu** [comment]
@S3phi40T yes but not every python comes with it out of the box. look at the list of modules that need installing on windows https://github.com/sealemar/BingRewards/pull/342

**Comment by S3phi40T** [comment]
@specu You are right! I'm forgetting there are non-Linux users in here.
In case of concerns, OpenVPN based VPN I use with Raspberry PI works like a charm.

**Comment by elisiano** [comment]
As @baltimoron mentioned, all necessary python dependencies should go into `requirements.txt` so that `pip install -r requirements.txt` can install them all.

@specu as mentioned in another thread/issue, integrating upstream projects within another is not tenable. 

If a portable way of running this is needed, you can generate a docker container (there is already a [`Dockerfile`](https://github.com/sealemar/BingRewards/blob/master/Dockerfile) at the root of the project and instructions are part of the [README](https://github.com/sealemar/BingRewards/blob/master/README.md).
Until @amayer5125 sets up automatic building with DockerHub I'm maintaining the image manually (you can `docker pull elisiano/bingrewards`)

Last but not least, the python requests module *does* support proxy. Although you can set that up programmatically, you can transparently make it use a proxy just by setting environment variables. See the official [documentation](http://docs.python-requests.org/en/master/user/advanced/#proxies) for more info.

**Comment by specu** [comment]
I'm not sure what integration are we talking about. Proxy settings are contained within config file and all the http requests except that single one that used requests module respect those settings.

**Comment by specu** [comment]
@gstreak please dont forget to close if this is no longer an issue
