### ISSUE TITLE
Mobile Searches Running But No Points

### ISSUE THREAD

**Issue by z0oinks** [sealemar/BingRewards#350]
For my first account, mobile searches are running, but I'm not getting any points for them.
It also doesn't error out at all.

**Comment by specu** [comment]
that's not a problem with the script. they want you to run it manually for a day or 2, in my opinion.

**Comment by z0oinks** [comment]
Weird. It was working for a while and just stopped today

**Comment by S3phi40T** [comment]
@z0oinks have you tried forcing Pixel user agent for your mobile searches?
Works like a charm for me since double points for mobile Edge searches. 
<ua_mobile><![CDATA[Mozilla/5.0 (Linux; Android 8.0; Pixel XL Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.145 Mobile Safari/537.36 EdgA/41.0.0.1273]]></ua_mobile>

**Comment by z0oinks** [comment]
Looks like it decided to start working again, not that I changed anything. Closed I guess!
