### ISSUE TITLE
No Points for Desktop and Mobile Searches

### ISSUE THREAD

**Issue by dronenb** [sealemar/BingRewards#360]
Is anyone else having this issue? I'm earning points for the daily set links, but I'm not earning any search points.  The script appears to be running fine, as it says it is completing both the desktop and mobile searches. However, no points are being earned.

**Comment by AMTNate** [comment]
I'm having the same issue as well.

**Comment by specu** [comment]
all my accounts are running fine, earning points and streaks

**Comment by AMTNate** [comment]
All three of my accounts are having this issue.

**Comment by aliasfoxkde** [comment]
I'm having the same issue, sort of. I don't seem to be earning all the points and I didnt note the error I was receiving this morning. The script also did several retries. I'm trying again now and will update with the error if it happens again. Maybe a server issue, because it seems to be working okay right now.

**Comment by aliasfoxkde** [comment]
I had this issue running bots last night, but I retrieve them today and everything finished fine (there was one retry which is bine and I received the remainder of points).

**Comment by dronenb** [comment]
Hmm.  Weird.  It wasn't working for at least three days, but it started working again this morning. I'm wondering if this is something on Microsoft's end.  Either way, I'll close this issue since it doesn't appear to be an issue with the script itself.
